version: 2
project_name: chiko

builds:
  - id: chiko
    main: ./cmd/chiko
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

release:
  github:
    owner: felangga
    name: chiko

brews:
  - name: chiko
    homepage: "https://github.com/felangga/chiko"
    description: "A simple TUI gRPC client"
    dependencies:
      - "go"

changelog:
  use: true
