# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chiko < Formula
  desc "A simple TUI gRPC client"
  homepage "https://github.com/felangga/chiko"
  version "0.0.1"
  license "MIT"

  depends_on "go"

  on_macos do
    on_intel do
      url "https://github.com/felangga/chiko/releases/download/v0.0.1/chiko_0.0.1_darwin_amd64.tar.gz"
      sha256 "04b1f2252ed9110c400878117668459f2f27ba42b0e25abe6d8035138d7b7908"

      def install
        bin.install "chiko"
      end
    end
    on_arm do
      url "https://github.com/felangga/chiko/releases/download/v0.0.1/chiko_0.0.1_darwin_arm64.tar.gz"
      sha256 "505efe9a5e9c5f11e936cb512760e6eeb8b3148150d802458181fa1c17b1e02b"

      def install
        bin.install "chiko"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/felangga/chiko/releases/download/v0.0.1/chiko_0.0.1_linux_amd64.tar.gz"
        sha256 "aaf0e6eb0c8cb2b3c74965e06d5600192bbd82479ee7c82f61f6f94fc0bc024e"

        def install
          bin.install "chiko"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/felangga/chiko/releases/download/v0.0.1/chiko_0.0.1_linux_arm64.tar.gz"
        sha256 "dc12a137dd8d0dc3d5cd4ebdd1f202d683667b11a9eaa21e9f8ac687cc000afb"

        def install
          bin.install "chiko"
        end
      end
    end
  end
end
